package com.kgc.tiku.bluebird;

public class Constant1
{
    public static final String ACTIONBEGIN = "actionBegin";
    public static final String ACTIONCLIENT = "actionClient";
    public static final String ACTIONEND = "actionEnd";
    public static final String ACTIONNAME = "actionName";
    public static final String ACTIONPREPEND = "actionPrepend";
    public static final String ACTIONTEST = "actionTest";
    public static final String ACTIONTYPE = "actionType";
    public static final String ACTIONTYPE_VALUE = "11";
    public static final String ACTIONVALUE = "actionValue";
    public static final String ACTION_FINISH_LOGINACTIVITY = "action.finishlogin";
    public static final String ACTION_TEST_FALSE = "0";
    public static final String ACTION_TEST_TRUE = "1";
    public static final String ACTION_UPDATEMSGUI = "action.updatemsgui";
    public static final int ACTIVITY_REQUEST_CODE_CHOOSE_HEAD_IMAGE_WAY = 23;
    public static final int ACTIVITY_RESULT_CODE_CHOOSE_HEAD_IMAGE_WAY_CAMERA = 21;
    public static final int ACTIVITY_RESULT_CODE_CHOOSE_HEAD_IMAGE_WAY_GALLERY = 22;
    public static final int AGAIN_LOGIN = 483;
    public static String AUTH;
    public static String BDQN;
    public static String BDQN_IMG_PATH;
    public static String BDQN_QUESTION_BANK;
    public static int BYTE = 0;
    public static String CHAPTERCODE;
    public static String CHOICEPRODUCT;
    public static String CHOICEPRODUT;
    public static String CHOICESCORE;
    public static String CLIENTNAME;
    public static String CLIENTTYPE;
    public static String CLIENTT_PUSHCOMPANY_PUSH;
    public static String CLIENT_ID_PUSH;
    public static String CLIENT_TYPE_PUSH;
    public static String CLIENT_VERSION_NAME;
    public static String CLIENT_VERSION_VALUE;
    public static String CN_B;
    public static String CN_K;
    public static String CORELESSON;
    public static String COURSEID;
    public static String COURSEWARECODE;
    public static String COURSEWAREID;
    public static String CURRENTDEF;
    public static String CURRENTLINENUMBER;
    public static String DEFSTR;
    public static String DESCRIPTION;
    public static String DOWN_QNYKT_APK;
    public static String ENCRYPT;
    public static final int EXAMINING = 1002;
    public static final int EXAMNONE = 1001;
    public static String EXAMRESULTID;
    public static String EXAMTYPE;
    public static String FILEPATH;
    public static String FUXIAUTO;
    public static String HOSTTYPE;
    public static final String IFEQUIPMENT = "ifEquipment";
    public static String ISBLOCK;
    public static String ISCOLLECT;
    public static String ISLOGINEXIT;
    public static String ISNOREADONLY;
    public static String ISOPENPRODUCTDIALOG;
    public static String IS_PRODUCT_NOTICE;
    public static String IS_PRODUCT_STOP;
    public static String IS_QUESTION_NOTICE;
    public static String IS_QUESTION_STOP;
    public static String JINENGAUTO;
    public static String JSESSIONID;
    public static final int LACK_NO = 481;
    public static String LASTVIDEOHEADURL;
    public static final String LAST_REGISTERLIVING_TIME = "last_registerliving_time";
    public static String LESSONLOCATION;
    public static String LINEADDRESS;
    public static String LINEHIGHTSPEED;
    public static String LINEISOPEN;
    public static String LINELOWSPEED;
    public static String LINENAME;
    public static final int LONG_NOT_FIND = 404;
    public static final int LONG_NOT_OPERATE = 480;
    public static String LRCBUTTON;
    public static String MECHANISM;
    public static String MESSAGEID;
    public static String MESSAGETYPES;
    public static final int MESSAGETYPE_ANSWER = 4;
    public static final int MESSAGETYPE_NOTICE = 3;
    public static final int MESSAGETYPE_SUGGEST = 5;
    public static String MONI;
    public static String MONTHORWEEK;
    public static String NOTICEID;
    public static String ONLINETIME;
    public static String OSTYPE;
    public static String OSVERSION;
    public static String OUTLINECODE;
    public static String OUTLINEID;
    public static String PAGE;
    public static String PAGENO;
    public static String PAGESIZE;
    public static String PAPERID;
    public static String PARENTID;
    public static String PASSPORT;
    public static String PASSPORTS;
    public static String PASSWORD;
    public static String PLAYFINISH;
    public static String PRODUCTID;
    public static String QUESTIONID;
    public static String QUESTIONIDS;
    public static String SAVEPOSTION;
    public static String SAVEPRODUCTID;
    public static final int SERVER_DEV = 1;
    public static final int SERVER_NORMAL = 3;
    public static final int SERVER_TEST = 2;
    public static String SHAREDNAME;
    public static String SIZE;
    public static String SKILLDOWNPOINTID;
    public static String SKILLID;
    public static String SKILLPOINTID;
    public static String STORAGETYPE;
    public static String SUBMITWAY;
    public static boolean SWITCHPRODUCTS = false;
    public static String TIGGERPOINT;
    public static String TOTALSCORE;
    public static String UNIFIEDID;
    public static String UNIFYPAGERHASS;
    public static String UNIFYPAGERTITLE;
    public static String UNIFYTESTENDTIME;
    public static String UNITRESULTJSON;
    public static String URL;
    public static final String USERACTION_DOWNLOADVIDEO = "downloadVideo";
    public static final String USERACTION_UPDATEVERSION = "updateVersion";
    public static final String USERSID = "userSID";
    public static final String USERUID = "userUID";
    public static final String USERUIP = "userUIP";
    public static String USER_NAME_SAVE;
    public static String USER_PASSWORD_SAVE;
    public static String USER_TYPE_SAVE;
    public static String USESECOND;
    public static String VERSION_UP_URL;
    public static String VIDEO_HEAD_CURRENT_URL;
    public static String VIDEO_HEAD_URL;
    public static String YL005_;
    
    static {
        Constant1.URL = "http://a.bdqn.dev.cn/pb";
        Constant1.VIDEO_HEAD_CURRENT_URL = "videoHeadCurrentUrl";
        Constant1.VIDEO_HEAD_URL = "http://admin-flv.bdqn.dev.cn/";
        Constant1.VERSION_UP_URL = "http://api.bdqn.dev.cn/html/version.xml";
        Constant1.LINEISOPEN = "lineIsOpen";
        Constant1.LINENAME = "lineName";
        Constant1.LINEADDRESS = "lineAddress";
        Constant1.LINELOWSPEED = "lineLowSpeed";
        Constant1.LINEHIGHTSPEED = "lineHeightSpeed";
        Constant1.CURRENTLINENUMBER = "currentLineNumber";
        Constant1.LASTVIDEOHEADURL = "lastVideoHeadUrl";
        Constant1.CURRENTDEF = "currentDef";
        Constant1.DEFSTR = "defStr";
        Constant1.DOWN_QNYKT_APK = "http://download.bdqn.cn/mobile_qnykt/qnykt";
        Constant1.BDQN_QUESTION_BANK = "http://exam.kgc.dev.cn/";
        Constant1.BDQN_IMG_PATH = "http://home.bdqn.dev/pd/";
        Constant1.BDQN = "bdqn";
        Constant1.BYTE = 1024;
        Constant1.SHAREDNAME = "user";
        Constant1.CHOICEPRODUCT = "choiceProduct";
        Constant1.PASSPORT = "passport";
        Constant1.PASSPORTS = "passports";
        Constant1.PASSWORD = "password";
        Constant1.OSTYPE = "osType";
        Constant1.PAGE = "page";
        Constant1.SIZE = "size";
        Constant1.PAGENO = "pageNo";
        Constant1.PAGESIZE = "pageSize";
        Constant1.CLIENT_ID_PUSH = "mobileDevice.clientId";
        Constant1.CLIENT_TYPE_PUSH = "mobileDevice.type";
        Constant1.CLIENTT_PUSHCOMPANY_PUSH = "mobileDevice.pushCompany";
        Constant1.MESSAGEID = "messageId";
        Constant1.NOTICEID = "noticeId";
        Constant1.LESSONLOCATION = "lessonLocation";
        Constant1.ONLINETIME = "onlineTime";
        Constant1.OSVERSION = "osVersion";
        Constant1.MECHANISM = "mechanism";
        Constant1.STORAGETYPE = "storageType";
        Constant1.MESSAGETYPES = "messageTypes";
        Constant1.ISNOREADONLY = "isNoReadOnly";
        Constant1.CHOICEPRODUT = "choiceProdut";
        Constant1.CLIENTTYPE = "clientType";
        Constant1.CLIENTNAME = "009";
        Constant1.CLIENT_VERSION_NAME = "version";
        Constant1.CLIENT_VERSION_VALUE = "Version_1.1.3";
        Constant1.USER_NAME_SAVE = "user_name_login";
        Constant1.USER_TYPE_SAVE = "user_type_login";
        Constant1.JSESSIONID = "JSESSIONID";
        Constant1.USER_PASSWORD_SAVE = "user_password_login";
        Constant1.IS_QUESTION_STOP = "is_question_stop";
        Constant1.IS_QUESTION_NOTICE = "is_question_notice";
        Constant1.IS_PRODUCT_STOP = "is_product_stop";
        Constant1.IS_PRODUCT_NOTICE = "is_product_notice";
        Constant1.ENCRYPT = "encrypt";
        Constant1.YL005_ = "_yl005_";
        Constant1.AUTH = "auth";
        Constant1.PRODUCTID = "productId";
        Constant1.OUTLINEID = "outlineId";
        Constant1.OUTLINECODE = "outlineCode";
        Constant1.SKILLID = "skillId";
        Constant1.ISBLOCK = "isBlock";
        Constant1.SAVEPRODUCTID = "saveproductid";
        Constant1.EXAMTYPE = "examType";
        Constant1.UNIFIEDID = "unifiedId";
        Constant1.COURSEID = "courseId";
        Constant1.PLAYFINISH = "playFinish";
        Constant1.LRCBUTTON = "lrcButton";
        Constant1.SWITCHPRODUCTS = false;
        Constant1.UNITRESULTJSON = "unitresultjson";
        Constant1.SKILLPOINTID = "skillPointId";
        Constant1.SKILLDOWNPOINTID = "skillpointId";
        Constant1.TIGGERPOINT = "tiggerPoint";
        Constant1.COURSEWAREID = "coursewareId";
        Constant1.FILEPATH = "filePath";
        Constant1.COURSEWARECODE = "coursewareCode";
        Constant1.DESCRIPTION = "description";
        Constant1.CORELESSON = "coreLesson";
        Constant1.USESECOND = "useSecond";
        Constant1.ISOPENPRODUCTDIALOG = "isOpenProductDialog";
        Constant1.ISLOGINEXIT = "isLoginExit";
        Constant1.PAPERID = "paperId";
        Constant1.CHOICESCORE = "choiceScore";
        Constant1.TOTALSCORE = "totalScore";
        Constant1.UNIFYTESTENDTIME = "unifyTestEndtime";
        Constant1.UNIFYPAGERTITLE = "unifyPagerTitle";
        Constant1.UNIFYPAGERHASS = "unifyPagerHasS";
        Constant1.SUBMITWAY = "submitWay";
        Constant1.EXAMRESULTID = "examResultId";
        Constant1.QUESTIONID = "questionId";
        Constant1.QUESTIONIDS = "questionIds";
        Constant1.MONTHORWEEK = "monthOrWeek";
        Constant1.FUXIAUTO = "fuxiAuto";
        Constant1.JINENGAUTO = "jinengAuto";
        Constant1.MONI = "moni";
        Constant1.HOSTTYPE = "hosttype";
        Constant1.SAVEPOSTION = "savepostion";
        Constant1.PARENTID = "parentId";
        Constant1.CHAPTERCODE = "chapterCode";
        Constant1.ISCOLLECT = "isCollect";
    }
    
    public static void setHostType(final int n) {
        switch (n) {
            case 1: {
                Constant1.URL = "http://a.bdqn.dev.cn/pb";
                Constant1.VIDEO_HEAD_URL = "http://admin-flv.bdqn.dev.cn/";
                Constant1.VERSION_UP_URL = "http://download.bdqn.dev.cn/version.xml";
                Constant1.DOWN_QNYKT_APK = "http://download.bdqn.dev.cn/qnykt";
                Constant1.BDQN_QUESTION_BANK = "http://exam.kgc.dev.cn/testing/";
                break;
            }
            case 2: {
                Constant1.URL = "http://a-test.bdqn.cn/pb";
                Constant1.VIDEO_HEAD_URL = "http://admin-flv.bdqn.cn/";
                Constant1.VERSION_UP_URL = "http://api-test.bdqn.cn/qingniao-test/version.xml";
                Constant1.DOWN_QNYKT_APK = "http://download.bdqn.cn/mobile_qnykt/qnykt";
                Constant1.BDQN_QUESTION_BANK = "http://exam-test.kgc.cn/testing/";
                break;
            }
            case 3: {
                Constant1.URL = "http://a.bdqn.cn/pb";
                Constant1.VIDEO_HEAD_URL = "http://admin-flv.bdqn.cn/";
                Constant1.VERSION_UP_URL = "http://api.bdqn.cn/qingniao/version.xml";
                Constant1.DOWN_QNYKT_APK = "http://download.bdqn.cn/mobile_qnykt/qnykt";
                Constant1.BDQN_QUESTION_BANK = "http://tiku.kgc.cn/testing/";
                break;
            }
        }
    }
}
